export class Brochure{
    constructor(
        public id: string, //index generated by firebase
        public title: string,
        public sport: string,
        public brochurePDF: File,
        public dateCreated: Date = new Date(),
        public username?: string, 
        public url?: any
    ){}
}